#!/bin/sh

# We only need a single processor to print hello, so ppn=1.
# A modest timeout of 1 minute is used, which should be
# plenty of time for this job to complete.

#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:01:00
#PBS -N mystery-valentine
#PBS -j oe

# Enter the directory where this script (and our executable) is.
cd "$PBS_O_WORKDIR"

# Run the executable.
./mystery-valentine > ~/job_output.txt
